# Artificial Neural Network -- Regression


### Importing the libraries

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [ ]:
tf.__version__

'2.18.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [ ]:
dataset = pd.read_excel("Folds5x2_pp.xlsx")
print(dataset.head(5))
X = dataset[['AT', 'V', 'AP', 'RH']].values
y = dataset[['PE']].values
print(X)
print(y)

      AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90
[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[[463.26]
 [444.37]
 [488.56]
 ...
 [429.57]
 [435.74]
 [453.28]]


### Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

## Part 2 - Building the ANN

### Initializing the ANN

In [ ]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=1))

## Part 3 - Training the ANN

### Compiling the ANN

In [ ]:
ann.compile(optimizer='adam', loss='mean_squared_error', metrics=['accuracy'])

### Training the ANN model on the Training set

In [ ]:
ann.fit(X_train, y_train, epochs=100)

Epoch 1/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.0000e+00 - loss: 27.7320
Epoch 2/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: 26.7998
Epoch 3/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 26.4976
Epoch 4/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 26.6555
Epoch 5/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 26.6244
Epoch 6/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 26.9077
Epoch 7/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 27.4678
Epoch 8/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 26.0158
Epoch 9/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0000e+00 - loss: 26.6447
Epoch 10/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0000e+00 - loss: 26.8016
Epoch 11/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0000e+00 - 

### Predicting the results of the Test set

In [ ]:
y_pred = ann.predict(X_test)
for pred, actual in zip(y_pred, y_test):
  print(f'[{pred}, {actual}]')

60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
[[430.8017], [431.23]]
[[461.9658], [460.01]]
[[464.84207], [461.14]]
[[449.08047], [445.9]]
[[460.0583], [451.29]]
[[429.54333], [432.68]]
[[471.05347], [477.5]]
[[457.7755], [459.68]]
[[474.51752], [477.5]]
[[443.98526], [444.99]]
[[441.90298], [444.37]]
[[442.13922], [437.04]]
[[446.4827], [442.34]]
[[441.12317], [440.74]]
[[437.24716], [436.55]]
[[455.77472], [460.24]]
[[447.6424], [448.66]]
[[437.05435], [432.94]]
[[450.3104], [452.82]]
[[428.406], [432.2]]
[[424.93118], [430.96]]
[[429.96768], [434.65]]
[[477.86588], [473.56]]
[[436.06696], [434.47]]
[[446.01624], [450.92]]
[[453.03818], [452.82]]
[[478.1043], [485.94]]
[[445.60297], [435.47]]
[[451.98834], [448.96]]
[[466.1217], [465.89]]
[[475.2779], [482.52]]
[[462.4892], [465.05]]
[[474.3937], [475.51]]
[[467.36453], [466.71]]
[[468.56387], [472.42]]
[[433.71402], [434.64]]
[[464.20554], [467.97]]
[[482.8901], [481.86]]
[[433.5613], [437.72]]
[[471.91833], [470.49]]
[[446.93774], [449.04

In [ ]:
from sklearn.metrics import mean_squared_error, r2_score
mse = mean_squared_error(y_test, y_pred.flatten())
print("Mean Squared Error (MSE):", mse)

r2 = r2_score(y_test, y_pred.flatten())
print("R² Score:", r2)

Mean Squared Error (MSE): 24.756741047532664
R² Score: 0.9153580489765941
